# Generated by Django 4.2.16 on 2024-09-06 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supreceipt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_receipt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('subprice_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supreceipt.supreceipt')),
            ],
        ),
    ]
