# Generated by Django 4.2.16 on 2024-09-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalReciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_receipt', models.IntegerField(blank=True, null=True)),
                ('n_order', models.IntegerField(default=1)),
                ('res_fk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
    ]
