# Generated by Django 4.2.16 on 2024-09-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalreceipt', '0005_alter_totalreciept_total_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalreciept',
            name='total_receipt',
            field=models.IntegerField(null=True),
        ),
    ]
