# Generated by Django 4.2.16 on 2024-09-09 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('totalreceipt', '0006_alter_totalreciept_total_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totalreciept',
            name='subprice_fk',
        ),
    ]
