# Generated by Django 4.2.16 on 2024-09-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('totalreceipt', '0007_remove_totalreciept_subprice_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalreciept',
            name='total_receipt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
