# Generated by Django 4.2.16 on 2024-09-10 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_alter_restaurant_img'),
        ('totalreceipt', '0008_alter_totalreciept_total_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='totalreciept',
            name='res_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
    ]
