# Generated by Django 4.2.16 on 2024-09-10 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('totalreceipt', '0001_initial'),
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supreceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('totalsupprice', models.IntegerField(null=True)),
                ('food_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('size_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sizes.size')),
                ('total_reciet_fk', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='totalreceipt.totalreciept')),
            ],
        ),
    ]
