# Generated by Django 4.2.16 on 2024-09-12 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supreceipt', '0001_initial'),
        ('totalreceipt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supreceipt',
            name='total_reciet_fk',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='totalreceipt.totalreciept'),
        ),
    ]
