# Generated by Django 4.2.16 on 2024-09-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supreceipt', '0002_alter_supreceipt_totalsupprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supreceipt',
            name='totalsupprice',
            field=models.IntegerField(null=True),
        ),
    ]
