# Generated by Django 4.2.16 on 2024-09-09 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('supreceipt', '0003_alter_supreceipt_totalsupprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='supreceipt',
            name='user_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
