# Generated by Django 4.2.16 on 2024-09-09 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('totalreceipt', '0007_remove_totalreciept_subprice_fk'),
        ('supreceipt', '0004_supreceipt_user_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='supreceipt',
            name='total_reciet_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='totalreceipt.totalreciept'),
        ),
    ]
