# Generated by Django 4.2.16 on 2024-09-09 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supreceipt', '0007_alter_supreceipt_total_reciet_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supreceipt',
            name='user_fk',
        ),
    ]
