# Generated by Django 4.2.16 on 2024-09-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=13)),
                ('address', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='restaurant_images/')),
            ],
        ),
    ]
