# Generated by Django 4.2.16 on 2024-09-08 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_adminn_admin_alter_customuser_options'),
        ('restaurant', '0003_alter_restaurant_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='admin_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.admin'),
        ),
    ]
