# Generated by Django 4.2.16 on 2024-09-08 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0006_alter_restaurant_admin_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='admin_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
