# Generated by Django 4.2.16 on 2024-09-10 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready')], default='pending', max_length=30)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('owner_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupsowner', to=settings.AUTH_USER_MODEL)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupsusername', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
