# Generated by Django 4.2.16 on 2024-09-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('confirmed', 'confirmed')], default='pending', max_length=30),
        ),
    ]
