# Generated by Django 4.2.16 on 2024-09-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_alter_pickup_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickup',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
