# Generated by Django 4.2.16 on 2024-09-09 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pickup', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickup',
            name='owner_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickupsowner', to=settings.AUTH_USER_MODEL),
        ),
    ]
