<<<<<<< HEAD
# Generated by Django 4.2.16 on 2024-09-09 09:30

=======
# Generated by Django 4.2.16 on 2024-09-09 09:36

from django.conf import settings
>>>>>>> dev
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('users', '0002_rename_adminn_admin_alter_customuser_options'),
=======
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
>>>>>>> dev
        ('sizes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='owner_fk',
<<<<<<< HEAD
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.owner'),
=======
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
>>>>>>> dev
        ),
    ]
