# Generated by Django 4.2.16 on 2024-09-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='food_images/'),
        ),
    ]
