# Generated by Django 4.2.16 on 2024-09-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0003_alter_pickup_owner_fk'),
        ('sizes', '0003_alter_size_owner_fk'),
        ('users', '0002_rename_adminn_admin_alter_customuser_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='admin_fk',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='customuser_ptr',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='res_fk',
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
